// ENTRY
export const SET_ENTRY = 'SET_ENTRY';
export const CREATE_ENTRY = 'CREATE_ENTRY';
export const UPDATE_ENTRY = 'UPDATE_ENTRY';
export const DELETE_ENTRY = 'DELETE_ENTRY';

// EARNINGS
export const GET_EARNING = 'GET_EARNING';
export const GET_EARNINGS = 'GET_EARNINGS';

// EXPENDITURES
export const GET_EXPENDITURE = 'GET_EXPENDITURE';
export const GET_EXPENDITURES = 'GET_EXPENDITURES';

// USER
export const GET_USER_DETAILS = 'GET_USER_DETAILS';

// BOOKMARKS
export const GET_BOOKMARKS = 'GET_BOOKMARKS';
export const BOOKMARK_EARNING = 'BOOKMARK_EARNING';
export const BOOKMARK_EXPENDITURE = 'BOOKMARK_EXPENDITURE';

// BUTTON
export const SET_BUTTON_CSS = 'SET_BUTTON_CSS';
export const GET_BUTTON_CSS = 'GET_BUTTON_CSS';

